"""Concept visualisation engine (separate from answer analysis).

Produces a multi-slide visual deck per subtopic. Slide kinds:
  - mindmap     — radial map: the concept at the centre, branches + leaves
  - definition  — hard terms broken down: formal → plain words → analogy
  - flow        — flowchart of the mechanism (nodes + arrows)
  - animation   — step-through bar animation, ONLY for genuine processes

Guardrails (enforced in code, never trusted to the model):
- 2-6 slides; first valid slide must exist or a deterministic fallback deck is used.
- mindmap: 3-6 branches, 1-5 children each; branch labels ≤6 words, leaves ≤10 words.
- definition: 1-4 terms; formal ≤35 words, simple ≤30, analogy ≤30.
- flow: 3-10 nodes, labels ≤8 words; edges must reference existing node ids.
- animation: kept only when the model flags the concept animatable AND supplies
  2-10 structurally valid frames. Invalid slides are dropped, not repaired by guesswork.
"""

from __future__ import annotations

import json

from sqlalchemy.orm import Session

from app.models.models import ConceptMap, Subtopic, Topic
from app.services.algorithm_animations import algorithm_animation_slide
from app.services.scene_animations import scene_animation_slide
from app.services.answer_analysis import _validate_frames
from app.services.llm import FallbackLLM

CONCEPT_SYSTEM = """TASK:concept_map
You create a multi-slide VISUAL study deck for ONE subtopic. Reply ONLY with JSON:
{"slides": [ ...2 to 5 slides... ]}

EVERY slide MUST also include a "narration" field: a spoken script for a
voice-over that plays while this slide is on screen, like a NotebookLM video
narrator. Write it to be SPOKEN, not read — warm, plain, flowing sentences,
25-55 words, no bullet points, no markdown. It should explain what the viewer
is looking at and why it matters, not just repeat the labels.

Slide kinds and their exact shapes:

1. MINDMAP (required, always the first slide — the big picture):
{"kind":"mindmap","title":str,"center":str,"narration":str,
 "branches":[{"label":str,"children":[str,...]}]}
- 4-6 branches covering the whole concept (what it is, how it works, key terms,
  where it's used, pitfalls, related ideas).
- branch label: MAX 6 words. children: 2-4 per branch, each a concrete fact or
  example, MAX 10 words. No filler like "various things".

2. DEFINITION (include when the subtopic has difficult terms/jargon):
{"kind":"definition","title":str,"narration":str,
 "terms":[{"term":str,"formal":str,"simple":str,"analogy":str}]}
- 2-4 of the hardest terms in this subtopic.
- formal: the textbook definition, MAX 35 words.
- simple: same idea in everyday words a 12-year-old gets, MAX 30 words.
- analogy: a vivid real-world comparison, MAX 30 words.

3. FLOW (include when there is a mechanism/sequence/causal chain):
{"kind":"flow","title":str,"narration":str,
 "nodes":[{"id":str,"label":str,"detail":str}],
 "edges":[{"from":str,"to":str,"label":str}]}
- 4-9 nodes, label MAX 8 words (a pointer, not a sentence), detail MAX 12 words.
- edges follow the actual order/causality; edge label MAX 3 words or "".

4. ANIMATION (ONLY if the concept is a step-by-step process whose state can be
honestly shown as changing bars — sorting, searching, scheduling, queues,
iterative optimisation. Definitions/taxonomies are NEVER animatable):
{"kind":"animation","title":str,"narration":str,
 "frames":[{"note":str,"values":[numbers],"highlights":[ints],"merged":[ints]}]}
- 4-8 frames, note MAX 20 words describing that exact step, 5-8 bars, values 1-99.

Deck rules: slide 1 = mindmap. Then choose the 1-4 other slides that genuinely
teach THIS subtopic best. Be specific and content-rich — real facts, real terms,
real steps. Never pad with generic slides. Give every slide a narration."""


def _inject_algorithm_slide(payload: dict, topic: Topic, subtopic: Subtopic) -> dict:
    """If this subtopic maps to a hand-built visual — a known algorithm (bar
    animation) or a curated scene (DNA, atoms, waves, graphs…) — swap it in.
    Computed in code, not by the LLM, so it's always correct. Done at read time
    so it stays fresh even for previously-cached decks."""
    blurb = subtopic.blurb or ""
    built = (algorithm_animation_slide(topic.name, subtopic.name, blurb)
             or scene_animation_slide(topic.name, subtopic.name, blurb))
    if not built:
        return payload
    # drop any generic LLM animation/scene and insert ours right after the mindmap
    slides = [s for s in payload.get("slides", []) if s.get("kind") not in ("animation", "scene")]
    insert_at = 1 if slides and slides[0].get("kind") == "mindmap" else 0
    slides = slides[:insert_at] + [built] + slides[insert_at:]
    return {**payload, "slides": slides}


def get_concept_map(db: Session, llm: FallbackLLM, subtopic: Subtopic, topic: Topic) -> dict:
    cached = db.query(ConceptMap).filter(ConceptMap.subtopic_id == subtopic.id).first()
    # Serve cache unless it's stale: generated by mock fallback, or pre-slides shape.
    if cached and cached.provider != "mock" and "slides" in cached.payload:
        return {**_inject_algorithm_slide(cached.payload, topic, subtopic), "provider": cached.provider, "cached": True}

    raw = llm.complete_json(CONCEPT_SYSTEM, json.dumps({
        "topic": topic.name,
        "subtopic": subtopic.name,
        "blurb": subtopic.blurb,
    }))
    slides = _validate_slides(raw)

    if cached:
        if llm.last_provider == "mock" and "slides" in cached.payload:
            return {**_inject_algorithm_slide(cached.payload, topic, subtopic), "provider": cached.provider, "cached": True}
        db.delete(cached)
        db.flush()

    if not slides:
        slides = _fallback_deck(subtopic)

    payload = {
        "subtopicId": subtopic.id,
        "name": subtopic.name,
        "topicName": topic.name,
        "slides": slides,
    }
    db.add(ConceptMap(subtopic_id=subtopic.id, provider=llm.last_provider, payload=payload))
    db.commit()
    return {**_inject_algorithm_slide(payload, topic, subtopic), "provider": llm.last_provider, "cached": False}


# ─── Validation ──────────────────────────────────────────────────────────────

def _clip(text, max_words: int, max_chars: int) -> str:
    words = str(text).strip().rstrip(".").split()
    return " ".join(words[:max_words])[:max_chars]


def _narration(s: dict, derived: str) -> str:
    """Spoken voice-over for a slide. Use the model's narration when it gave a
    usable one, otherwise fall back to a script derived from the slide content
    so the video overview always has something to say."""
    raw = str(s.get("narration", "")).strip()
    if len(raw.split()) >= 6:
        # keep it speakable: cap length, don't hard-truncate mid-word
        words = raw.split()
        return " ".join(words[:60])
    return derived


def _validate_slides(raw: dict) -> list[dict]:
    slides_in = raw.get("slides")
    if not isinstance(slides_in, list):
        return []
    out: list[dict] = []
    seen_animation = False
    for s in slides_in[:6]:
        if not isinstance(s, dict):
            continue
        kind = s.get("kind")
        v = None
        if kind == "mindmap":
            v = _v_mindmap(s)
        elif kind == "definition":
            v = _v_definition(s)
        elif kind == "flow":
            v = _v_flow(s)
        elif kind == "animation" and not seen_animation:
            v = _v_animation(s)
            seen_animation = v is not None
        if v:
            out.append(v)
    # a deck must lead with a mindmap; tolerate wrong ordering by re-sorting
    out.sort(key=lambda x: 0 if x["kind"] == "mindmap" else 1)
    return out[:6]


def _v_mindmap(s: dict) -> dict | None:
    branches_in = s.get("branches")
    if not isinstance(branches_in, list) or not 2 <= len(branches_in) <= 8:
        return None
    branches = []
    for b in branches_in[:6]:
        if not isinstance(b, dict) or not str(b.get("label", "")).strip():
            return None
        children = [
            _clip(c, 10, 70) for c in (b.get("children") or [])[:5]
            if isinstance(c, str) and c.strip()
        ]
        if not children:
            return None
        branches.append({"label": _clip(b["label"], 6, 44), "children": children})
    if len(branches) < 2:
        return None
    center = _clip(s.get("center", ""), 5, 36) or "Concept"
    derived = (
        f"Let's start with the big picture of {center}. "
        f"It breaks down into {len(branches)} parts — "
        + ", ".join(b["label"] for b in branches)
        + ". Keep these branches in mind as we go deeper."
    )
    return {
        "kind": "mindmap",
        "title": _clip(s.get("title", "The big picture"), 8, 60) or "The big picture",
        "center": center,
        "branches": branches,
        "narration": _narration(s, derived),
    }


def _v_definition(s: dict) -> dict | None:
    terms_in = s.get("terms")
    if not isinstance(terms_in, list) or not terms_in:
        return None
    terms = []
    for t in terms_in[:4]:
        if not isinstance(t, dict):
            continue
        term = str(t.get("term", "")).strip()
        formal, simple = str(t.get("formal", "")).strip(), str(t.get("simple", "")).strip()
        if not term or not formal or not simple:
            continue
        terms.append({
            "term": _clip(term, 6, 48),
            "formal": _clip(formal, 35, 240),
            "simple": _clip(simple, 30, 210),
            "analogy": _clip(t.get("analogy", ""), 30, 210),
        })
    if not terms:
        return None
    first = terms[0]
    derived = (
        f"Now the words that trip people up. Take {first['term']}: "
        f"{first['simple']}"
        + (f" Think of it like {first['analogy'].rstrip('.')}." if first["analogy"] else "")
    )
    return {
        "kind": "definition",
        "title": _clip(s.get("title", "Hard words, simply"), 8, 60) or "Hard words, simply",
        "terms": terms,
        "narration": _narration(s, derived),
    }


def _v_flow(s: dict) -> dict | None:
    nodes_in = s.get("nodes")
    if not isinstance(nodes_in, list) or not 3 <= len(nodes_in) <= 10:
        return None
    nodes, ids = [], set()
    for n in nodes_in[:10]:
        if not isinstance(n, dict):
            return None
        nid = str(n.get("id", "")).strip()[:30]
        label = str(n.get("label", "")).strip()
        if not nid or nid in ids or not label:
            return None
        ids.add(nid)
        nodes.append({"id": nid, "label": _clip(label, 8, 60), "detail": _clip(n.get("detail", ""), 12, 90)})
    edges = []
    for e in (s.get("edges") or [])[:14]:
        if not isinstance(e, dict):
            continue
        a, b = str(e.get("from", "")).strip()[:30], str(e.get("to", "")).strip()[:30]
        if a in ids and b in ids and a != b:
            edges.append({"from": a, "to": b, "label": _clip(e.get("label", ""), 3, 24)})
    derived = (
        "Here's how it actually works, step by step. We start at "
        f"{nodes[0]['label']} and follow the arrows through to "
        f"{nodes[-1]['label']}. Watch how each stage feeds the next."
    )
    return {
        "kind": "flow",
        "title": _clip(s.get("title", "How it works"), 8, 60) or "How it works",
        "nodes": nodes,
        "edges": edges,
        "narration": _narration(s, derived),
    }


def _v_animation(s: dict) -> dict | None:
    frames = _validate_frames(s.get("frames"))
    if not frames:
        return None
    dumped = [f.model_dump() for f in frames]
    derived = (
        "Now let's watch it run. "
        f"{dumped[0]['note'].rstrip('.')}. "
        f"Follow the highlighted bars across all {len(dumped)} steps to the finish."
    )
    return {
        "kind": "animation",
        "title": _clip(s.get("title", "Watch it run"), 8, 60) or "Watch it run",
        "frames": dumped,
        "narration": _narration(s, derived),
    }


def _fallback_deck(subtopic: Subtopic) -> list[dict]:
    name = subtopic.name
    return [
        {
            "kind": "mindmap",
            "title": "The big picture",
            "center": name,
            "branches": [
                {"label": "What it is", "children": [subtopic.blurb[:70] or "The core idea", "Why it matters"]},
                {"label": "How it works", "children": ["The mechanism, step by step", "The order things happen in"]},
                {"label": "Watch out for", "children": ["The mistakes most students make", "Edge cases that break intuition"]},
                {"label": "Where it's used", "children": ["Typical problems it solves", "Real-world applications"]},
            ],
            "narration": (
                f"Let's map out {name}. There are four things worth holding onto: "
                "what it is, how it works, what to watch out for, and where it's used. "
                "Connect the AI engine for a deeper, subject-specific walkthrough."
            ),
        },
        {
            "kind": "definition",
            "title": "Hard words, simply",
            "terms": [{
                "term": name,
                "formal": subtopic.blurb or f"The formal definition of {name}.",
                "simple": f"{name}, explained in plain words — connect the AI engine for a real breakdown.",
                "analogy": "",
            }],
            "narration": (
                f"Here's {name} in plain words. This is the offline preview — "
                "turn on the AI engine and you'll get the real terms broken down "
                "with everyday analogies."
            ),
        },
    ]
